from django.utils.translation import ugettext_lazy as _
from model_utils import Choices


PUBLISHED_STATE = Choices(
    ('DRAFT', _('Draft')),
    ('PUBLISHED', _('Published')),
    ('SUSPENDED', _('Suspended')),
)


ADDRESS_TYPE = Choices(
    ('DEFAULT_ADDRESS', _('Default Address')),
    ('SHIPPING_ADDRESS', _('Shipping Address')),
    ('INVOICE_ADDRESS', _('Invoice Address')),
)

BILLING_SOURCE = Choices(
    (1, "X_COMMERCE", _("XCommerce")),
    (2, "LMS", _("LMS")),
    (3, "SHOPEE", _("Shopee")),
    (4, "LAZADA", _("Lazada")),
    (5, "SALE", _("Sale"))
)

UNIT_PRODUCT_TYPE = Choices(
    (1, "COURSE", _("คอร์ส")),
    (2, "SET", _("ชุด")),
    (3, "BOOK", _("เล่ม")),
    (4, "FILE", _("ไฟล์")),
    (5, "ITEM", _("ชื้น")),
    (6, "CARD", _("ใบ")),
    (7, "TIME", _("ครั้ง")),
    (8, "STICK", _("แท่ง")),
    (9, "UNIT", _("Unit ")),
)
PRODUCT_TYPE = Choices(
    (1, "COURSE", _("Course")),
    (2, "BUNDLE", _("Course Bundle")),
    (3, "COURSE_BOOK", _("Course Book")),
    (4, "SIMULATION", _("Simulation Test")),
    (5, "EDUGADGETS", _("EduGadgets")),
    (6, "BUNDLE_EDUGADGETS", _("Bundle EduGadgets")),
    (7, "COURSE_SERVICE", _("Course Service")),
    (8, "FB_PRIVATE_GROUP", _("[Facebook] Private Group")),
    (9, "E_DOCUMENT", _("E-Document")),
    (10, "EXTERNAL_COURSE", _("External - [Course]")),
    (11, "EXTERNAL_EXAM", _("External - [Exam]")),
    (12, "SUPPORT_SALE", _("ส่งเสริมการขาย")),
    (13, "DEPOSIT", _("ค่ามัดจำ")),
    (14, "SHIPPING_COST", _("ค่าจัดส่ง")),
    (15, "COURSE_EDUGADGET", _("Course EduGadget")),
    (999, "DISCOUNT", _("ส่วนลด")),
)

THAI_PROVICE = Choices(
    (37, "AMNAT_CHAROEN", _("Amnat Charoen")),
    (15, "ANGTHONG", _("Ang Thong")),
    (14, "AYUTTHAYA", _("Phra Nakhon Si Ayutthaya")),
    (10, "BANGKOK", _("Bangkok")),
    (38, "BUENG_KAN", _("Bueng Kan")),
    (31, "BURI_RAM", _("Buriram")),
    (24, "CHACHOENGSAO", _("Chachoengsao")),
    (36, "CHAIYAPHUM", _("Chaiyaphum")),
    (18, "CHAI_NAT", _("Chai Nat")),
    (22, "CHANTHABURI", _("Chanthaburi")),
    (50, "CHIANG_MAI", _("Chiang Mai")),
    (57, "CHIANG_RAI", _("Chiang Rai")),
    (20, "CHON_BURI", _("Chonburi")),
    (86, "CHUMPHON", _("Chumphon")),
    (46, "KALASIN", _("Kalasin")),
    (62, "KAMPHAENG_PHET", _("Kamphaeng Phet")),
    (71, "KANCHANABURI", _("Kanchanaburi")),
    (40, "KHON_KEAN", _("Khon Kean")),
    (81, "KRABI", _("Krabi")),
    (52, "LAMPANG", _("Lampang")),
    (51, "LAMPHUN", _("Lamphun")),
    (42, "LOEI", _("Loei")),
    (16, "LOPBURI", _("Lopburi")),
    (58, "MAE_HONG_SON", _("Mae Hong Son")),
    (44, "MAHASARAKHAM", _("Maha Sarakham")),
    (49, "MUKDAHAN", _("Mukdahan")),
    (26, "NAKHON_NAYOK", _("Nakhon Nayok")),
    (73, "NAKHON_PATHOM", _("Nakhon_Pathom")),
    (48, "NAKHON_PHANOM", _("Nakhon Phanom")),
    (30, "NAKHON_RATCHASIMA", _("Nakhon Ratchasima")),
    (60, "NAKHON_SAWAN", _("Nakhon Sawan")),
    (80, "NAKHON_SI_THAMMARAT", _("Nakhon Si Thammarat")),
    (55, "NAN", _("Nan")),
    (96, "NARATHIWAT", _("Narathiwat")),
    (39, "NONGBUALAMPHU", _("Nong Bua Lamphu")),
    (43, "NONGKHAI", _("Nong Khai")),
    (12, "NONTHABURI", _("Nonthaburi")),
    (13, "PATHUM_THANI", _("Pathum Thani")),
    (94, "PATTANI", _("Pattani")),
    (82, "PHANGNGA", _("Phang Nga")),
    (93, "PHATTHALUNG", _("Phatthalung")),
    (56, "PHAYAO", _("Phayao")),
    (67, "PHETCHABUN", _("Phetchabun")),
    (76, "PHETCHABURI", _("Phetchaburi")),
    (66, "PHICHIT", _("Phichit")),
    (65, "PHITSANULOK", _("Phitsanulok")),
    (54, "PHRAE", _("Phrae")),
    (83, "PHUKET", _("Phuket")),
    (25, "PRACHINBURI", _("Prachinburi")),
    (77, "PRACHUAP_KHIRI_KHAN", _("Prachuap Khiri Khan")),
    (85, "RANONG", _("Ranong")),
    (70, "RATCHABURI", _("Ratchaburi")),
    (21, "RAYONG", _("Rayong")),
    (45, "ROI_ET", _("Roi Et")),
    (47, "SAKONNAKHON", _("Sakon Nakhon")),
    (11, "SAMUTPRAKAN", _("Samut Prakan")),
    (74, "SAMUT_SAKHON", _("Samut Sakhon")),
    (75, "SAMUT_SONGKHRAM", _("Samut Songkhram")),
    (19, "SARABURI", _("Saraburi")),
    (91, "SATUN", _("Satun")),
    (17, "SINGBURI", _("Sing Buri")),
    (33, "SISAKET", _("Sisaket")),
    (90, "SONGKHLA", _("Songkhla")),
    (27, "SRA_KAEO", _("Sra Kaeo")),
    (64, "SUKHOTHAI", _("Sukhothai")),
    (72, "SUPHANBURI", _("Suphan Buri")),
    (84, "SURAT_THANI", _("Surat Thani")),
    (32, "SURIN", _("Surin")),
    (63, "TAK", _("Tak")),
    (92, "TRANG", _("Trang")),
    (23, "TRAT", _("Trat")),
    (34, "UBON_RATCHATHANI", _("Ubon Ratchathani")),
    (41, "UDONTHANI", _("Udon Thani")),
    (61, "UTHAITHANI", _("Uthai Thani")),
    (53, "UTTARADIT", _("Uttaradit")),
    (95, "YALA", _("Yala")),
    (35, "YASOTHON", _("Yasothon")),
)
