# Generated by Django 3.0.10 on 2022-02-20 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import livefield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live', livefield.fields.LiveField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('title', models.CharField(blank=True, max_length=300, null=True, verbose_name='Title')),
                ('away_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='away_team', to='team.Team', verbose_name='Away Team')),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_created_user', to=settings.AUTH_USER_MODEL, verbose_name='Created User')),
                ('home_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='home_team', to='team.Team', verbose_name='Home Team')),
                ('updated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_updated_user', to=settings.AUTH_USER_MODEL, verbose_name='Edited User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
