# Generated by Django 3.0.10 on 2022-02-20 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import livefield.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name': 'Match Board', 'verbose_name_plural': 'Match Board'},
        ),
        migrations.CreateModel(
            name='LiveLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live', livefield.fields.LiveField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('link', models.CharField(blank=True, max_length=300, null=True, verbose_name='Link')),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livelink_created_user', to=settings.AUTH_USER_MODEL, verbose_name='Created User')),
                ('updated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livelink_updated_user', to=settings.AUTH_USER_MODEL, verbose_name='Edited User')),
            ],
            options={
                'verbose_name': 'Live Link',
                'verbose_name_plural': 'Live Link',
            },
        ),
        migrations.AddField(
            model_name='match',
            name='live_link',
            field=models.ManyToManyField(to='match.LiveLink', verbose_name='Live Link'),
        ),
    ]
