# Generated by Django 3.0.10 on 2022-02-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_auto_20220221_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='livelink',
            name='logo',
            field=models.ImageField(default=1, upload_to='static/images/live_logo'),
            preserve_default=False,
        ),
    ]
